### ISSUE TITLE
Cross Site Request Forgery protection needed

### ISSUE THREAD

**Issue by brackendawson** [members-area/members-area#39]
I may be wrong, but I think cross site requests are possible, eg:
http://www.googledrive.com/host/0B95eTj3CondTb1o3Q0RkRk0xMUk

**Comment by benjie** [comment]
I've not checked; but I don't recall implementing CSRF tokens (easy to do with the [csrf middleware](http://www.senchalabs.org/connect/csrf.html)) so you're probably right.
