### ISSUE TITLE
Got 400 - "Invalid POST data" when initialising a tag.

### ISSUE THREAD

**Issue by brackendawson** [members-area/members-area#40]
I'm hitting the check at https://github.com/members-area/members-area/blob/master/plugins/members-area-rfid-tags/controllers/rfid-tags.coffee#L29 with a post such as the below, I think that's working out if tags is a key? Not sure why it's not. 

<pre>
{
    "tags": {
        "9b8785b5": {
            "assigned_user": null,
            "count": 1,
            "sector_a_key_a": "a2V5IGEA",
            "sector_a_key_b": "a2V5IGIA",
            "sector_a_secret": "W24WtMW/Jg2QE5MP/M99uW2NIZfv/c8=",
            "sector_a_sector": 1,
            "sector_b_key_a": "a2V5IGEA",
            "sector_b_key_b": "a2V5IGIA",
            "sector_b_secret": "+2/RY/AWfq3nial2SUA3IkceDzXSMk0=",
            "sector_b_sector": 2
        }
    }
}
</pre>

This post copied from my testserver program's store, the one it received over the wire will have not been formatted for humans.

**Comment by brackendawson** [comment]
The json is the same as the test at https://github.com/members-area/members-area/blob/master/plugins/members-area-rfid-tags/test/controllers/rfid-tag.coffee#L50, but the test uses a PUT method. Going to try that real quick.

**Comment by brackendawson** [comment]
PUT is worse:
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 501.
<p>Message: Unsupported method ('PUT').
<p>Error code explanation: 501 = Server does not support this operation.
</body>

**Comment by benjie** [comment]
Are you sending `Content-Type: application/json`?

**Comment by brackendawson** [comment]
Yep, that fixed it.
