### ISSUE TITLE
users keys is empty when tag has an assigned user.

### ISSUE THREAD

**Issue by brackendawson** [members-area/members-area#41]
I init'd a tag and it does appear in the database. But after assigning it to myself, users is empty in the get:

<pre>
u'{"tags":{"9b8785b5":{"sector_a_key_a":"a2V5IGEA","sector_b_key_a":"a2V5IGEA","sector_b_key_b":"a2V5IGIA","sector_a_secret":"3MvNiRbWbQ6iAU+cUMTzVa2a8+LTk9Q=","sector_b_secret":"UHa93sFJ5r97kO20EmRSkIQ0jgkkQQk=","sector_b_sector":2,"sector_a_sector":1,"sector_a_key_b":"a2V5IGIA","assigned_user":"000003","count":1}},"users":{}}'
</pre>

Also, please make sure assigned_user and the keys under the user key are padded the same. I'm willing to make that value an int.

**Comment by benjie** [comment]
Oops :)

**Comment by brackendawson** [comment]
Woooo, that works now thanks. Going to assume fixed by c361da0
