### ISSUE TITLE
RFID: Not seeing "entries" logged.

### ISSUE THREAD

**Issue by brackendawson** [members-area/members-area#42]
Currently I'm sending scans like:

<pre>
{
    "tags": {
        "035a53b6": {
            "count": 97,
            "scans": [
                {
                    "assigned_user": "00001",
                    "date": 1446571012,
                    "location": "DOOR1",
                    "result": "denied"
                }
            ]
        },
        "65f909b4": {
            "count": 2,
            "scans": [
                {
                    "assigned_user": "00003",
                    "date": 1446581579,
                    "location": "DOOR1",
                    "result": "allowed"
                }
            ]
        },
        "7bae0dcb": {
            "count": 2,
            "scans": [
                {
                    "assigned_user": "00003",
                    "date": 1446581584,
                    "location": "DOOR1",
                    "result": "allowed"
                }
            ]
        }
    }
}
</pre>

**Comment by brackendawson** [comment]
I think it only logs if there's two elements in the array in the scans key.

**Comment by brackendawson** [comment]
I was POSTing the data before appending scans, the scans would be deferred to the next POST, I don't know why they didn't get there. Possibly the background poll sent them up without an updated count.

Do we want to add the success field to the UI?

**Comment by benjie** [comment]
Yeah, the UI needs an overhaul but it's not vital at this stage (though relatively trivial to add). Feel free to file it as another issue (or send a PR :wink: )

[Relevant view code](https://github.com/members-area/members-area/blob/b64a126a22f1055450abcd50130cabe403ccb04e/plugins/members-area-rfid-tags/views/rfid-tags/settings.jade#L37-L43)

[Relevant model fields](https://github.com/members-area/members-area/blob/b64a126a22f1055450abcd50130cabe403ccb04e/plugins/members-area-rfid-tags/models/rfidentry.coffee#L16-L32)
