### ISSUE TITLE
Add ability to logout

### ISSUE THREAD

**Issue by jlowe64** [members-area/members-area#46]
This enhancement would improve security of use of website in public spaces. It would allow users to log out of their accounts, allowing another person to log in.

**Comment by benjie** [comment]
Turns out we already have this at `/logout` - just don't link to it anywhere. PR welcome :smile:

**Comment by jlowe64** [comment]
I'll try to do it today!

**Comment by jlowe64** [comment]
Yeah, I just checked the template today and it was up in the top right-hand side already. I'm not entirely sure why I didn't see it on this day. I will close this as it's pointless!
